# Generated by Django 5.0.1 on 2024-03-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bestsellers_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestsellers',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bestsellers',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
